language: ruby
rvm:
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - jruby-19mode
  - rbx-19mode
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
    - rvm: ruby-head
notifications:
  irc: "irc.freenode.org#adhearsion"
sudo: true
before_install:
  - sudo apt-get install libpcap-dev -y
